[package]
name = "entity_object_book"
version = "0.1.0"
edition = "2021"

[dependencies]
value_object_book = { workspace = true }
value_object_division = { workspace = true }
value_object_user = { workspace = true }
chrono = { workspace = true }
